// web-vuejs/src/pages/reservation/page-reservations/cadre-calendrier/cadre-calendrier.vue
<!-- Le tableau des réservations-->
<template>
	<v-layout wrap align-center>

		<!-- Le tableau des réservations-->
		<v-flex class="xs12 d-flex">
			<h3 v-t="'reservations_titre_calendrier'"></h3>
		</v-flex>

		<!-- Entete principal-->
		<v-flex class="xs12 d-flex tableauDonnees entete" v-if="!flagSaisieDatesPersonalisees">

			<span class="boutonsAction">
				<v-tooltip bottom>
					<template #activator="data"><em class="fa fa-angle-double-left" @click="deplacerDateParJour(-14);"></em></template>
					<span v-t="'calendrier_tooltip_moinsMoins'"></span>
				</v-tooltip>
				<v-tooltip bottom>
					<template #activator="data"><em class="fa fa-angle-left" @click="deplacerDateParJour(-7);"></em></template>
					<span v-t="'calendrier_tooltip_moins'"></span>
				</v-tooltip>
			</span>

			<!-- Dates de début et fin-->
			<span v-t="'reservations_form_du'"></span>&nbsp;
			<span> {{dateDebut.date | dateCourte}} </span>&nbsp;
			<span v-t="'reservations_form_au'"></span>&nbsp;
			<span> {{dateFin.date | dateCourte}}</span>

			<span class="boutonsAction">
				<v-tooltip bottom>
					<template #activator="data"><em class="fa fa-angle-right" @click="deplacerDateParJour(7);"></em></template>
					<span v-t="'calendrier_tooltip_plus'"></span>
				</v-tooltip>
				<v-tooltip bottom>
					<template #activator="data"><em class="fa fa-angle-double-right" @click="deplacerDateParJour(14);"></em></template>
					<span v-t="'calendrier_tooltip_plusPlus'"></span>
				</v-tooltip>
				<v-tooltip bottom>
					<template #activator="data"><em class="fa fa-calendar" @click="deplacerDateParDefaut();"></em></template>
					<span v-t="'calendrier_tooltip_dateParDefaut'"></span>
				</v-tooltip>
				<v-tooltip bottom>
					<template #activator="data"><em class="fa fa-search" @click="flagSaisieDatesPersonalisees=true"></em></template>
					<span v-t="'commun_tooltip_rechercher'"></span>
				</v-tooltip>
				<v-tooltip bottom>
					<template #activator="data"><em class="fa fa-plus" @click="initaliserNouvelleReservation()"></em></template>
					<span v-t="'commun_tooltip_ajouter'"></span>
				</v-tooltip>
			</span>
		</v-flex>

		<!-- Entete secondaire-->
		<v-flex class="xs12 d-flex tableauDonnees entete" v-if="flagSaisieDatesPersonalisees">

			<!-- Date de début -->
			<span class="libelleDatePicker" v-t="'reservations_form_du'"></span>
			<v-menu v-model="dateDebut.datePick" :close-on-content-click="false" :nudge-right="40" lazy transition="scale-transition" offset-y class="petitdatepicker"
			        full-width min-width="100px">
				<template v-slot:activator="{ on }">
					<v-text-field v-model="dateDebut.dateCourte" readonly v-on="on"></v-text-field>
				</template>
				<v-date-picker v-model="dateDebut.dateComplete" @input="dateDebut.datePick = false"></v-date-picker>
			</v-menu>

			<!-- Date de fin -->
			<span class="libelleDatePicker" v-t="'reservations_form_au'"></span>
			<v-menu v-model="dateFin.datePick" :close-on-content-click="false" :nudge-right="40" lazy transition="scale-transition" offset-y class="petitdatepicker"
			        full-width min-width="100px">
				<template v-slot:activator="{ on }">
					<v-text-field v-model="dateFin.dateCourte" readonly v-on="on"></v-text-field>
				</template>
				<v-date-picker v-model="dateFin.dateComplete" @input="dateFin.datePick = false"></v-date-picker>
			</v-menu>

			<span class="boutonsAction">
				<v-tooltip bottom>
					<template #activator="data"><em class="fa fa-search" @click="chargerDonnees();"></em></template>
					<span v-t="'commun_tooltip_rechercher'"></span>
				</v-tooltip>
				<v-tooltip bottom>
					<template #activator="data"><em class="fa fa-ban" @click="flagSaisieDatesPersonalisees=false"></em></template>
					<span v-t="'commun_tooltip_annuler'"></span>
				</v-tooltip>

				<v-tooltip bottom>
					<template #activator="data"><em class="fa fa-plus" @click="initaliserNouvelleReservation()"></em></template>
					<span v-t="'commun_tooltip_ajouter'"></span>
				</v-tooltip>
			</span>
		</v-flex>

		<!-- Ligne des chambres -->
		<v-flex class="xs12 d-flex tableauDonnees enteteTableau">
			<v-flex class="xs2 d-flex"><span v-t="'reservations_header_date'"></span></v-flex>
			<v-flex :class="'d-flex xs' + nbColParChambre" v-for="c of chambres" :key="c.reference"><span>{{c.nom}}</span></v-flex>
		</v-flex>

		<!-- Tableau de données-->
		<v-flex :class="(j.getDay()==0||j.getDay()==6)?'xs12 d-flex tableauDonnees ligneCal weekend':'xs12 d-flex tableauDonnees ligneCal'" v-for="j of jours"
		        :key="j.time">
			<v-flex class="xs2 d-flex"><span>{{j.getDate()}}/{{j.getMonth() + 1}}</span></v-flex>
			<v-flex :class="'d-flex xs'+ nbColParChambre" v-for="c of chambres" :key="c.reference">
				<!-- Case avec une reservation -->
				<div class="reservation" :style="reservations[c.reference][j.toISOString()].style" v-if="!!reservations[c.reference] && !!reservations[c.reference][j.toISOString()]"
				     @click="afficherDetail(reservations[c.reference][j.toISOString()].reservation)">
					<span>{{reservations[c.reference][j.toISOString()].texte}}</span>
				</div>
				<!-- Case sans reservation -->
				<div v-if="!reservations[c.reference] || !reservations[c.reference][j.toISOString()]" @click="afficherDetail(undefined)"></div>
			</v-flex>
		</v-flex>
	</v-layout>
</template>

<script lang="ts" src="./cadre-calendrier.ts"/>
<style scoped lang="scss" src="./cadre-calendrier.scss"/>

// web-angular/src/app/reservations/page-reservations/cadre-calendrier/cadre-calendrier.component.ts
import { Component, OnInit, EventEmitter } from '@angular/core';
import { Language } from 'angular-l10n';

import { ReservationService } from '../../service/reservation.service';
import * as model from '../../model/model';

/** Page de gestion des reservations */
@Component({ selector: 'cadre-calendrier', templateUrl: './cadre-calendrier.component.html', styleUrls: ['./cadre-calendrier.component.css'] })
export class CadreCalendrierComponent implements OnInit {

  /** Decorateur nécessaire aux libellés internationnalisés dans des tooltips */
  @Language() lang: string;

  /** Bus de message pour communiquer avec le composant parent */
  busDeMessage = new EventEmitter<model.Reservation>();

  /** Filtre d'affichage - debut */
  dateDebut: Date;

  /** Filtre d'affichage - fin */
  dateFin: Date;

  /** Flag permettant la saisie de dates sur une période personnalisée */
  flagSaisieDatesPersonalisees: boolean = false;

  /** Largeur de la colonne d'une chambre */
  nbColParChambre = 2;

  /** Liste des réservations à afficher. */
  reservations: model.IStringToAnyMap<model.IStringToAnyMap<model.Reservation>> = {};

  /** Liste des chambres */
  chambres: model.Chambre[] = [];

  /** Liste des jours */
  jours: Date[];

  /** Un constructeur pour se faire injecter les dépendances */
  constructor(private reservationsService: ReservationService) { }

  /** A l'initialisation */
  ngOnInit() {

    // Initialisation des dates de filtrage (de J-3 à J+12)
    this.deplacerDateParDefaut();

  }

  /** revenir aux dates par défaut */
  deplacerDateParDefaut() {
    const dateDuJour = new Date();
    this.dateDebut = new Date(dateDuJour.getTime() - (3 * 1000 * 3600 * 24));
    this.dateFin = new Date(dateDuJour.getTime() + (12 * 1000 * 3600 * 24));

    // Chargement des données
    this.chargerDonnees();
  }

  /** Déplacement des dates du filtre en jour */
  deplacerDateParJour(n: number) {
    // Déplacement des dates du filtre
    this.dateDebut = new Date(this.dateDebut.getTime() + (n * 1000 * 3600 * 24));
    this.dateFin = new Date(this.dateFin.getTime() + (n * 1000 * 3600 * 24));

    // Chargement des données
    this.chargerDonnees();
  }

  /** Affichage du détail dans le formualaire */
  afficherDetail(reservation: model.Reservation | undefined) {
    // Pour prévenir le composant parent qu'une réservation est sélectionnée
    this.busDeMessage.emit(reservation);
  }

  /** Initialisation d'une nouvelle réservation */
  initaliserNouvelleReservation() {
    // Pour prévenir le composant parent qu'une réservation est sélectionnée
    this.busDeMessage.emit(new model.Reservation('', new Date(), new Date(), '', new model.Chambre('', ''), new model.Formule('', '', 0)));
  }

  /** Chargement de la liste des chambres, puis des réservations et calcul du tableau de données */
  chargerDonnees() {

    this.reservations = {};

    // Chargement des chambres
    this.reservationsService.listerChambres().subscribe(
      (chambres) => {
        if (chambres && chambres.length > 0) {
          this.chambres = chambres;
          this.nbColParChambre = Math.floor((12 - 2) / chambres.length);
        } else {
          this.chambres = [];
          this.nbColParChambre = 1;
        }

        // Chargement des réservations
        this.reservationsService.rechercherReservations(this.dateDebut, this.dateFin).subscribe(
          (reservations) => {

            // Calcul de la liste des jours entre la date de début et la date de fin
            this.jours = [];
            const d = new Date(this.dateDebut);
            while (d <= this.dateFin) {
              this.jours.push(new Date(d));
              d.setDate(d.getDate() + 1);
            }

            // Calcul du tableau de données
            for (const j of this.jours) {
              for (const c of this.chambres) {
                if (!this.reservations[c.reference]) {
                  this.reservations[c.reference] = {};
                }
                for (const r of reservations) {
                  if (r.chambre.reference === c.reference && r.dateDebut <= j && j <= r.dateFin) {
                    this.reservations[c.reference][j.toISOString()] = r;
                  }
                }
              }
            }
          }
        );
      }
    );
  }
}

<!-- Le tableau des réservations-->
<mat-card>
  <mat-card-title>
    <span l10nTranslate>reservations_titre_calendrier</span>
  </mat-card-title>
  <mat-card-content class="tableauDonnees">

    <!-- Entete principal-->
    <div class="row entete" *ngIf="!flagSaisieDatesPersonalisees">
      <div class="col-12">

        <span class="boutonsAction">
          <em class="fa fa-angle-double-left" (click)="deplacerDateParJour(-14);" matTooltip="{{ 'calendrier_tooltip_moinsMoins' | translate: lang }}"></em>
          <em class="fa fa-angle-left" (click)="deplacerDateParJour(-7);" matTooltip="{{ 'calendrier_tooltip_moins' | translate: lang }}"></em>
        </span>

        <!-- Dates de début et fin-->
        <span l10nTranslate>reservations_form_du</span>
        <span> {{dateDebut | date:'dd/MM'}} </span>
        <span l10nTranslate>reservations_form_au</span>
        <span> {{dateFin | date:'dd/MM'}}</span>

        <span class="boutonsAction">
          <em class="fa fa-angle-right" (click)="deplacerDateParJour(7);" matTooltip="{{ 'calendrier_tooltip_plus' | translate: lang }}"></em>
          <em class="fa fa-angle-double-right" (click)="deplacerDateParJour(14);" matTooltip="{{ 'calendrier_tooltip_plusPlus' | translate: lang }}"></em>
          <em class="fa fa-calendar" (click)="deplacerDateParDefaut();" matTooltip="{{ 'calendrier_tooltip_dateParDefaut' | translate: lang }}"></em>
          <em class="fa fa-search" (click)="flagSaisieDatesPersonalisees=true" matTooltip="{{ 'commun_tooltip_rechercher' | translate: lang }}"></em>
          <em class="fa fa-plus" (click)="initaliserNouvelleReservation()" matTooltip="{{ 'commun_tooltip_ajouter' | translate: lang }}"></em>
        </span>
      </div>
    </div>

    <!-- Entete secondaire-->
    <div class="row entete" *ngIf="flagSaisieDatesPersonalisees">
      <div class="col-12">

        <!-- Date de début -->
        <span class="libelleDatePicker" l10nTranslate>reservations_form_du</span>
        <mat-form-field class="datePickerLargeurAdaptee">
          <input matInput name="dateDebutPick" [matDatepicker]="dateDebutPick" [max]="dateFin" [(ngModel)]="dateDebut"
            required>
          <mat-datepicker-toggle matSuffix [for]="dateDebutPick"></mat-datepicker-toggle>
          <mat-datepicker #dateDebutPick disabled="false"></mat-datepicker>
        </mat-form-field>

        <!-- Date de fin -->
        <span class="libelleDatePicker" l10nTranslate>reservations_form_au</span>
        <mat-form-field class="datePickerLargeurAdaptee">
          <input matInput name="dateFinPick" [matDatepicker]="dateFinPick" [min]="dateDebut" [(ngModel)]="dateFin"
            required>
          <mat-datepicker-toggle matSuffix [for]="dateFinPick"></mat-datepicker-toggle>
          <mat-datepicker #dateFinPick disabled="false"></mat-datepicker>
        </mat-form-field>

        <span class="boutonsAction">
          <em class="fa fa-search" (click)="chargerDonnees();" matTooltip="{{ 'commun_tooltip_rechercher' | translate: lang }}"></em>
          <em class="fa fa-ban" (click)="flagSaisieDatesPersonalisees=false" matTooltip="{{ 'commun_tooltip_annuler' | translate: lang }}"></em>
          <em class="fa fa-plus" (click)="initaliserNouvelleReservation()" matTooltip="{{ 'commun_tooltip_ajouter' | translate: lang }}"></em>
        </span>
      </div>
    </div>

    <!-- Ligne des chambres -->
    <div class="row enteteTableau">
      <div class="col-2" l10nTranslate>reservations_header_date</div>
      <div [class]="'col-' + nbColParChambre" *ngFor="let c of chambres">{{c.nom}}</div>
    </div>

    <!-- Tableau de données-->
    <div [class]="(j.getDay()==0||j.getDay()==6)?'ligneCal row weekend':'ligneCal row'" *ngFor="let j of jours">
      <div class="col-2">{{j | date:'dd/MM'}}</div>
      <div [class]="'col-' + nbColParChambre" *ngFor="let c of chambres;">
        <!-- Case avec une reservation -->
        <div class="reservation" [style]="reservations[c.reference][j.toISOString()].style" *ngIf="!!reservations[c.reference] && !!reservations[c.reference][j.toISOString()]"
          (click)="afficherDetail(reservations[c.reference][j.toISOString()].reservation)">
          <span>{{reservations[c.reference][j.toISOString()].texte}}</span>
        </div>
        <!-- Case sans reservation -->
        <div *ngIf="!reservations[c.reference] || !reservations[c.reference][j.toISOString()]" (click)="afficherDetail(undefined)"></div>
      </div>
    </div>
  </mat-card-content>
</mat-card>
