// web-vuejs/src/pages/reservation/page-reservations/cadre-reservation/cadre-reservation.vue
<!-- Le formulaire de détail -->
<template>
	<v-layout wrap align-center v-if="!!reservationSelectionnee.reference || creation">

		<v-flex xs12 d-flex>
			<h3>
				<span v-t="'reservation_titre'"></span>
				<span>{{ reservationSelectionnee.reference.split('-')[1] }}</span>
			</h3>
		</v-flex>

		<v-form v-model="valide" @keyup.native.enter="valide && enregistrerReservationSelectionnee()" v-on:submit.prevent>

			<v-flex xs12 d-flex>
				max
				<!-- todo: [max]="reservationSelectionnee.dateFin" -->
				<span class="libelleDatePicker" v-t="'reservation_placeholder_dateDebut'"></span>
				<v-menu v-model="dateDebut.datePick" :close-on-content-click="false" :nudge-right="40" lazy transition="scale-transition" offset-y
				        class="petitdatepicker" full-width min-width="100px">
					<template v-slot:activator="{ on }">
						<v-text-field v-model="dateDebut.dateCourte" readonly v-on="on" :disabled="reservationSelectionnee.etatCourant==='TERMINEE'"></v-text-field>
					</template>
					<v-date-picker v-model="dateDebut.dateComplete" @input="dateDebut.datePick = false"></v-date-picker>
				</v-menu>
			</v-flex>

			<v-flex xs12 d-flex>
				min
				<!-- todo: [min]="reservationSelectionnee.dateDebut"-->
				<span class="libelleDatePicker" v-t="'reservation_placeholder_dateFin'"></span>
				<v-menu v-model="dateFin.datePick" :close-on-content-click="false" :nudge-right="40" lazy transition="scale-transition" offset-y class="petitdatepicker"
				        full-width min-width="100px">
					<template v-slot:activator="{ on }">
						<v-text-field v-model="dateFin.dateCourte" readonly v-on="on" :disabled="reservationSelectionnee.etatCourant==='TERMINEE'"></v-text-field>
					</template>
					<v-date-picker v-model="dateFin.dateComplete" @input="dateFin.datePick = false"></v-date-picker>
				</v-menu>
			</v-flex>

			<v-flex xs12 d-flex>
				<v-text-field type="number" required v-model="reservationSelectionnee.client" name="client" :rules="obligatoireRegles" :label="$t('reservation_placeholder_client')"
				              :disabled="reservationSelectionnee.etatCourant==='TERMINEE'"></v-text-field>
			</v-flex>

			<v-flex xs12 d-flex>
				<v-select :items="chambres" item-text="nom" item-value="reference" required v-model="reservationSelectionnee.chambre.reference" name="chambre"
				          :label="$t('reservation_placeholder_chambre')" :disabled="reservationSelectionnee.etatCourant==='TERMINEE'"></v-select>
			</v-flex>

			<v-flex xs12 d-flex>
				/prix/ €/nuit
				<!--todo libellé des options -->
				<v-select :items="formules" item-text="nom" item-value="reference" required v-model="reservationSelectionnee.formule.reference" name="formule"
				          :label="$t('reservation_placeholder_formule')" :disabled="reservationSelectionnee.etatCourant==='TERMINEE'"></v-select>
			</v-flex>

			<v-flex xs12 d-flex>
				<v-text-field type="number" required v-model="reservationSelectionnee.nombrePersonnes" name="nombrePersonnes" :rules="obligatoireRegles"
				              :label="$t('reservation_placeholder_nombrePersonnes')"></v-text-field>
			</v-flex>

			<v-flex xs12 d-flex v-for="(o, index) of options" :key="o.reference">
				<v-checkbox :name="'parNuit'+index" v-model="optionsCalculeesPourLaReservationSelectionnee[o.reference]" :disabled="reservationSelectionnee.etatCourant==='TERMINEE'">
					:label="o.nom+' '+o.prix+' '+'€'+(o.parNuit?' par nuit':'')+(o.parPersonne?' par personne':'')"</v-checkbox>
			</v-flex>

			<v-flex xs12 d-flex>
				<button @click="enregistrerReservationSelectionnee()" v-if="reservationSelectionnee.etatCourant!=='TERMINEE'" :disabled="!valide" v-t="'reservation_bouton_enregistrer'"></button>
				<button @click="changerEtatEnCours()" v-if="reservationSelectionnee.etatCourant==='ENREGISTREE'" v-t="'reservation_bouton_arriveeClient'"></button>
				<button @click="annulerOuFermer()" v-if="reservationSelectionnee.reference" v-t="'reservation_bouton_fermer'"></button>
				<button @click="annulerOuFermer()" v-if="!reservationSelectionnee.reference" v-t="'reservation_bouton_annuler'"></button>
			</v-flex>
		</v-form>
	</v-layout>
</template>

<script lang="ts" src="./cadre-reservation.ts"/>
<style scoped lang="scss" src="./cadre-reservation.scss"/>

// web-angular/src/app/reservations/page-reservations/cadre-reservation/cadre-reservation.component.ts
import { Component, OnInit, EventEmitter } from '@angular/core';
import { Language } from 'angular-l10n';

import { ReservationService } from '../../service/reservation.service';
import * as model from '../../model/model';

/** Page de gestion des reservations */
@Component({ selector: 'cadre-reservation', templateUrl: './cadre-reservation.component.html', styleUrls: ['./cadre-reservation.component.css'] })
export class CadreReservationComponent implements OnInit {

  /** Decorateur nécessaire aux libellés internationnalisés dans des tooltips */
  @Language() lang: string;

  /** Liste des chambres */
  chambres: model.Chambre[] = [];

  /** Reservation dans le détail */
  reservationSelectionnee: model.Reservation | undefined;

  /** Bus de message pour communiquer avec le composant parent */
  busDeMessage = new EventEmitter<string>();

  /** Un constructeur pour se faire injecter les dépendances */
  constructor(private reservationsService: ReservationService) { }

  /** A l'initialisation */
  ngOnInit() {
    this.reservationsService.listerChambres().subscribe(
      (chambres) => {
        if (chambres && chambres.length > 0) {
          this.chambres = chambres;
        } else {
          this.chambres = [];
        }
      });
  }

  enregistrerReservationSelectionnee() {
    if (this.reservationSelectionnee) {
      this.reservationsService.sauvegarderReservation(this.reservationSelectionnee).subscribe(() => {
        this.reservationSelectionnee = undefined;
        this.busDeMessage.emit('');
      });
    }
  }
}

<!-- Le formulaire de détail -->
<mat-card *ngIf="!!reservationSelectionnee">
  <mat-card-title *ngIf="reservationSelectionnee.reference">
    <span l10nTranslate>reservation_titre</span>
    <span>{{ reservationSelectionnee.reference.split('-')[1] }}</span>
  </mat-card-title>
  <mat-card-content>
    <form novalidate #leForm="ngForm" class="formFieldFullWidth">
      <div class="row">
        <mat-form-field>
          <input matInput name="dateDebutPickDetail" [matDatepicker]="dateDebutPickDetail" [max]="reservationSelectionnee.dateFin"
            [(ngModel)]="reservationSelectionnee.dateDebut" placeholder="{{ 'reservation_placeholder_dateDebut' | translate: lang }}"
            [disabled]="reservationSelectionnee.etatCourant==='TERMINEE'" required>
          <mat-datepicker-toggle matSuffix [for]="dateDebutPickDetail"></mat-datepicker-toggle>
          <mat-datepicker #dateDebutPickDetail disabled="false"></mat-datepicker>
        </mat-form-field>
      </div>
      <div class="row">
        <mat-form-field>
          <input matInput name="dateFinPickDetail" [matDatepicker]="dateFinPickDetail" [min]="reservationSelectionnee.dateDebut"
            [(ngModel)]="reservationSelectionnee.dateFin" placeholder="{{ 'reservation_placeholder_dateFin' | translate: lang }}"
            [disabled]="reservationSelectionnee.etatCourant==='TERMINEE'" required>
          <mat-datepicker-toggle matSuffix [for]="dateFinPickDetail"></mat-datepicker-toggle>
          <mat-datepicker #dateFinPickDetail disabled="false"></mat-datepicker>
        </mat-form-field>
      </div>
      <div class="row">
        <mat-form-field>
          <input matInput name="client" [(ngModel)]="reservationSelectionnee.client" placeholder="{{ 'reservation_placeholder_client' | translate: lang }}"
            [disabled]="reservationSelectionnee.etatCourant==='TERMINEE'" required>
        </mat-form-field>
      </div>
      <div class="row">
        <mat-form-field>
          <mat-select [(ngModel)]="reservationSelectionnee.chambre.reference" name="chambre" placeholder="{{ 'reservation_placeholder_chambre' | translate: lang }}"
            [disabled]="reservationSelectionnee.etatCourant==='TERMINEE'" required>
            <mat-option *ngFor="let c of chambres" [value]="c.reference">{{c.nom}}</mat-option>
          </mat-select>
        </mat-form-field>
      </div>
      <div class="row">
        <mat-form-field>
          <mat-select [(ngModel)]="reservationSelectionnee.formule.reference" name="formule" placeholder="{{ 'reservation_placeholder_formule' | translate: lang }}"
            [disabled]="reservationSelectionnee.etatCourant==='TERMINEE'" required>
            <mat-option *ngFor="let f of formules" [value]="f.reference">{{f.nom}} ({{f.prixParNuit}} €/nuit)</mat-option>
          </mat-select>
        </mat-form-field>
      </div>
      <div class="row">
        <mat-form-field>
          <input matInput type="number" name="nombrePersonnes" [(ngModel)]="reservationSelectionnee.nombrePersonnes"
            placeholder="{{ 'reservation_placeholder_nombrePersonnes' | translate: lang }}" [disabled]="reservationSelectionnee.etatCourant==='TERMINEE'"
            required>
        </mat-form-field>
      </div>
      <div class="row" *ngFor="let o of options; let i = index">
        <mat-checkbox name="parNuit{{i}}" [(ngModel)]="optionsCalculeesPourLaReservationSelectionnee[o.reference]"
          [disabled]="reservationSelectionnee.etatCourant==='TERMINEE'">
          {{o.nom}} {{o.prix}} €{{o.parNuit?' par nuit':''}}{{o.parPersonne?' par personne':''}}</mat-checkbox>
      </div>
      <div class="row">
        <button type="submit" (click)="enregistrerReservationSelectionnee()" class="btn btn-outline-secondary" *ngIf="reservationSelectionnee.etatCourant!=='TERMINEE'"
          [disabled]="!leForm.form.valid" l10nTranslate>reservation_bouton_enregistrer</button>

        <button type="submit" (click)="changerEtatEnCours()" class="btn btn-outline-secondary" *ngIf="reservationSelectionnee.etatCourant==='ENREGISTREE'"
          l10nTranslate>reservation_bouton_arriveeClient</button>

        <button type="submit" (click)="annulerOuFermer()" class="btn btn-outline-secondary" *ngIf="reservationSelectionnee.reference"
          l10nTranslate>reservation_bouton_fermer</button>
        <button type="submit" (click)="annulerOuFermer()" class="btn btn-outline-secondary" *ngIf="!reservationSelectionnee.reference"
          l10nTranslate>reservation_bouton_annuler</button>
      </div>
    </form>
  </mat-card-content>
</mat-card>
