// web-angular/src/app/reservations/page-consommations/page-consommations.component.ts
import { Component, OnInit } from '@angular/core';
import { Language } from 'angular-l10n';
import { Reservation } from '../model/model';

/** Page de gestion des reservations */
@Component({ selector: 'page-consommations', templateUrl: './page-consommations.component.html', styleUrls: ['./page-consommations.component.css'] })
export class PageConsommationsComponent {

  /** Decorateur nécessaire aux libellés internationnalisés dans des tooltips */
  @Language() lang: string;

  /** Liste des réservations en cours */
  reservations: Reservation;
}

<div class="container-fluid">
  <div class="row">

    <!-- Partie gauche : sélection -->
    <div class="col-8">
      <mat-card>
        <mat-card-title>
          <span l10nTranslate>consommations_titre_maincourante</span>
        </mat-card-title>
        <mat-card-content>

          <!-- liste des reservations -->
          <div class="row">
            <div class="col-12">
              <span l10nTranslate *ngIf="reservations && reservations.length == 0">consommations_titre_aucuneReservationEnCours</span>
              <mat-chip-list class="chipListSpaceEvenly chipListSelectionnable" [selectable]="true">
                <mat-chip *ngFor="let reservation of reservations" (click)="selectionnerReservation(reservation)"
                  [class.chipSelectionne]="reservationSelectionee === reservation">
                  <div>{{reservation.chambre.nom}} - {{reservation.client}}</div>
                </mat-chip>
              </mat-chip-list>
            </div>
          </div>

          <hr />

          <!-- liste des produits -->
          <div class="row">
            <div class="col-12">
              <mat-chip-list class="chipListSpaceEvenly chipListSelectionnable" [selectable]="true" *ngIf="reservationSelectionee">
                <mat-chip *ngFor="let produit of produits" [style.backgroundColor]="produit.couleur" (click)="ajouterConsomation(chambreSelectionee, produit)">
                  <div>{{produit.nom}}</div>
                </mat-chip>
              </mat-chip-list>
            </div>
          </div>
        </mat-card-content>
      </mat-card>
    </div>

    <!-- Partie droite : consommations de la réservation -->
    <div class="col-4" *ngIf="reservationSelectionee">
      <mat-card>
        <mat-card-title>
          <span>{{reservationSelectionee.chambre.nom}} - {{reservationSelectionee.client}}</span>
        </mat-card-title>
        <mat-card-content>
          <div *ngFor="let conso of consommationsDeLaReservationSelectionnee">
            <em class="fa fa-trash-alt" (click)="supprimerConsommation(conso)"></em>
            <em class="fa fa-angle-down" (click)="reduireConsommation(conso)"></em>
            &nbsp;
            <span>{{conso.quantite}} x {{conso.produit.nom}}</span>
          </div>
        </mat-card-content>
      </mat-card>
    </div>
  </div>
</div>

// web-vuejs/src/pages/reservation/page-consommations/page-consommations.vue
<template>
	<v-layout wrap align-center>

		<!-- Partie gauche : sélection -->
		<v-flex xs12 d-flex>
			<h3 v-t="'consommations_titre_maincourante'"></h3>
		</v-flex>

		<!-- liste des reservations -->
		<v-flex xs12 d-flex>
			<span v-if="reservations && reservations.length == 0" v-t="'consommations_titre_aucuneReservationEnCours'"></span>
			<v-chip class="chipReservation" v-for="reservation of reservations" :key="reservation.reference" @click="selectionnerReservation(reservation)"
			        :selected="reservationSelectionee && reservationSelectionee.reference===reservation.reference">
				<div class="contenuChipReservation">{{reservation.chambre.nom}} - {{reservation.client}}</div>
			</v-chip>
		</v-flex>

		<hr />

		<!-- liste des produits -->
		<v-flex xs12 v-if="reservationSelectionee && reservationSelectionee.reference">
			<div>
				<v-chip class="chipProduit" v-for="produit of produits" :key="produit.reference" :style="'backgroundColor:' + produit.couleur">
					<div class="quantiteDansChip">
						<span v-if="calculerQuantitePourProduit(produit.reference)">
							<em class="fa fa-trash-alt" @click="supprimerConsommation(produit.reference)"></em>
						</span>
						<span>{{calculerQuantitePourProduit(produit.reference)}}</span>
						<span v-if="calculerQuantitePourProduit(produit.reference)">
							<em class="fa fa-angle-down" @click="reduireConsommation(produit.reference)"></em>
						</span>
					</div>
					<div @click="ajouterConsomation(chambreSelectionee, produit)" class="nomProduit cliquable">{{produit.nom}}</div>
				</v-chip>
			</div>
		</v-flex>

	</v-layout>
</template>

<script lang="ts" src="./page-consommations.ts"/>
<style scoped lang="scss" src="./page-consommations.scss"/>
